# Site settings
title: "BLAST-Radius"
email: "blast.radius.attack@gmail.com"
description: >
  We have discovered a protocol vulnerability in RADIUS that allows a man-in-the-middle attacker to authenticate itself to a device using RADIUS for user authentication, or to assign itself arbitrary network privileges.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

collections_dir: pages
collections:
  abstract:
    output: true
  background:
    output: true
  attacks:
    output: true
  mitigation:
    output: true
  media:
    output: true
  questions:
    output: true

# Build settings
markdown: kramdown
mathjax: true
